[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ambitsentrydocs"
authors = [{name = "Ambit Team", email = "info@ambitsentry.com"}]
dynamic = ["version", "description"]
